version: '3.7'

services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: '${DATABASE_NAME}'
      MYSQL_USER: '${DATABASE_USER}'
      MYSQL_PASSWORD: '${DATABASE_PASS}'
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
    ports:
      - '3307:3306'

  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - '8000:8000'
    depends_on:
      - db
    environment:
      - "DJANGO_SECRET_KEY=${DOCKER_COMPOSE_DJANGO_SECRET_KEY}"
      - "DJANGO_DEBUG=${DOCKER_COMPOSE_DJANGO_DEBUG}"
      - "DJANGO_ZIBAL_MERCHANT_ID=${DOCKER_COMPOSE_DJANGO_ZIBAL_MERCHANT_ID}"
