# Generated by Django 5.0.2 on 2024-03-13 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='zarinpal_authority',
            new_name='zibal_authority',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='zarinpal_ref_id',
            new_name='zibal_ref_id',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='zarinpal_user_data',
            new_name='zibal_user_data',
        ),
    ]
