# Generated by Django 5.0 on 2023-12-30 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SwimmerCategory',
            new_name='TypeSwimCategory',
        ),
        migrations.RenameField(
            model_name='seasoncategory',
            old_name='swimmer_category',
            new_name='type_swim_category',
        ),
    ]
