# Generated by Django 5.0 on 2024-01-06 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_swimmercategory_typeswimcategory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method_name', models.CharField(choices=[('US', 'UNITED STATE OF AMERICA'), ('UK', 'UNITED KINGDOM'), ('AUS', 'AUSTRALIA'), ('CHN', 'CHINA')], max_length=255)),
                ('type_swimmer', models.CharField(choices=[('F', 'FAST'), ('SE', 'SEMI-ENDURANCE'), ('E', 'ENDURANCE')], max_length=255)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='seasoncategory',
            name='method_category',
        ),
        migrations.RemoveField(
            model_name='typeswimcategory',
            name='method_category',
        ),
        migrations.RemoveField(
            model_name='seasoncategory',
            name='type_swim_category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='season_category',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.category'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='MethodCategory',
        ),
        migrations.DeleteModel(
            name='TypeSwimCategory',
        ),
        migrations.DeleteModel(
            name='SeasonCategory',
        ),
    ]
