# Generated by Django 5.0 on 2024-01-17 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_category_remove_seasoncategory_method_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pdf_file',
            field=models.FileField(default=1, upload_to='product/product_pdf/'),
            preserve_default=False,
        ),
    ]
