# Generated by Django 5.0 on 2024-01-31 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_contact_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='email',
        ),
    ]
