# Generated by Django 5.0 on 2024-02-02 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_remove_contact_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
