# Generated by Django 5.0.2 on 2024-02-29 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_delete_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='type_swimmer',
            field=models.CharField(choices=[('سرعتی', 'FAST'), ('نیمه اسقامتی', 'SEMI-ENDURANCE'), ('استقامتی', 'ENDURANCE')], max_length=255),
        ),
    ]
