# Generated by Django 5.0.2 on 2024-02-29 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_category_type_swimmer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='type_swimmer',
            field=models.CharField(choices=[('F', 'FAST'), ('SE', 'SEMI-ENDURANCE'), ('E', 'ENDURANCE')], max_length=255),
        ),
    ]
