# Generated by Django 5.0.2 on 2024-03-18 11:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_category_type_swimmer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='pdf_file',
        ),
        migrations.AlterField(
            model_name='category',
            name='type_swimmer',
            field=models.CharField(choices=[('سرعتی', 'FAST'), ('نیمه استقامتی', 'SEMI-ENDURANCE'), ('استقامتی', 'ENDURANCE')], max_length=255),
        ),
        migrations.CreateModel(
            name='PurchaseFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_modified', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_files', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
