# Generated by Django 5.0.2 on 2025-03-24 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_remove_purchasefile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='method_name',
            field=models.CharField(choices=[('GYM', 'SWIM BODYBUILDING'), ('US', 'UNITED STATE OF AMERICA'), ('UK', 'UNITED KINGDOM'), ('AUS', 'AUSTRALIA'), ('CHN', 'CHINA')], max_length=255),
        ),
        migrations.AlterField(
            model_name='category',
            name='type_swimmer',
            field=models.CharField(choices=[('بانوان', 'FEMALE'), ('آقایان', 'MALE'), ('سرعتی', 'FAST'), ('نیمه استقامتی', 'SEMI-ENDURANCE'), ('استقامتی', 'ENDURANCE')], max_length=255),
        ),
    ]
